apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mesh-demo/backend:dev
        imagePullPolicy: Never
        env:
        - name: CODE_PATH
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 80
        volumeMounts:
        - name: backend-code
          mountPath: /app
      volumes:
      - name: backend-code
        hostPath:
          path: /Users/braedennorman/Documents/personal/simple-app/backend  
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: backend