apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: backend
        image: mesh-demo/backend:dev
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"
        volumeMounts:
        - mountPath: /app
          name: code-volume
      volumes:
      - name: code-volume
        hostPath:
          path: $CODE_ROOT/backend
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: backend